---
- block:
  - name: install python3 develop related tools
    apt: "pkg={{ packages }} state=latest"
    vars:
      packages:
      - build-essential
      - python3-dev
      - python3-venv
      - libncurses5-dev
      - libncursesw5-dev
      - libreadline-dev
      - libdb-dev
      - libgdbm-dev
      - libsqlite3-dev
      - libssl-dev
      - libbz2-dev
      - libexpat-dev
      - liblzma-dev
      - zlib1g-dev
      - uuid-dev
      - libffi-dev
      - tk-dev
  tags:
    - python3_dev
