---
- name: install develop tools
  apt: "pkg={{ item }} state=latest"
  with_items:
    - vim
    - build-essential
    - mosh
    - python3-dev
    - python-dev
    - virtualenv
    - libncurses5-dev
    - libncursesw5-dev
    - libreadline-dev
    - libdb-dev
    - libgdbm-dev
    - libsqlite3-dev
    - libssl-dev
    - libbz2-dev
    - libexpat-dev
    - liblzma-dev
    - zlib1g-dev
