---
- block:
  - name: install develop tools
    apt: "pkg={{ item }} state=latest"
    with_items:
      - vim
      - build-essential
      - mosh
      - tmux
      - fish
      - python3-dev
      - python3-venv
      - libncurses5-dev
      - libncursesw5-dev
      - libreadline-dev
      - libdb-dev
      - libgdbm-dev
      - libsqlite3-dev
      - libssl-dev
      - libbz2-dev
      - libexpat-dev
      - liblzma-dev
      - zlib1g-dev
  tags:
    - devtools
